# Site
name: 'aprende.'
description: 'The place where you can read about all contents. Collecting the valuable information that our authors have and publishing each content to you.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'ape-1'
email: 'aprende@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-admin
  
authors:
    ashfar:
      name:           Muhammed Ashfar
      site:           https://muhd.tk
      avatar:         /assets/images/muhammedashfar.jpg
      bio:            "Hi, I am Muhammed Ashfar, the author of aprende., the theme you're currently previewing. I hope you like it!"
      email:          muhammed.ashfar.7@gmail.com
      twitter:        https://twitter.com/ashfar_muhammed
      instagram:      https://www.instagram.com/b.lan.c/
      facebook:       https://facebook.com/muhammed.ashfar.4/
      github:         https://github.com/muhammedashfar7/ 
    mohammed:
      name:           Mohammed A
      site:           https://muhd.tk
      avatar:         /assets/images/mohammeda.jpg
      bio:            "Hi, I am Mohammed A, the author of aprende., the theme you're currently previewing. I hope you like it!"
      email:          mohammedalukkal123@gmail.com
      twitter:        https://twitter.com/
      instagram:      https://www.instagram.com//
      facebook:       https://facebook.com//
      github:         https://github.com//   
    sal:
      name:           Sal
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
